# Generated by Django 3.2 on 2023-03-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Articulo',
        ),
    ]
